baseurl = "https://oudeis.co/"
title = "oudeis"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5

[params]
  description = "Describe your website" # meta description
  author = "Edward Romano"
  authorLink = "https://oudeis.co/"
  bio = [
    "foo"
  ]
  copyright = [
    "&copy; 2018 Edward Romano",
    "Design customized from the Hugo [Nederburg](https://github.com/appernetic/hugo-nederburg-theme) theme.",
  ]

  # Gravitar author image
  email = "edward.romano@gmail.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "blog/"
  weight = 2

  [[menu.main]]
  name = "Projects"
  url = "projects/"
  weight = 3

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 4

  [params.social]
  email         = "oudeis.metis@gmail.com"
  twitter       = "https://twitter.com/oudeismetis"
  linkedin      = "https://www.linkedin.com/in/edromano/"
  stackoverflow = "https://stackoverflow.com/users/9173553/oudeis"
  github        = "https://github.com/oudeismetis"
  rss           = true
