baseurl = "https://www.oudeis.co/"
title = "oudeis"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-122222377-1"
preserveTaxonomyNames = true
paginate = 5

[params]
  description = "Projects and blog posts by Edward Romano" # meta description
  author = "Edward Romano"
  authorLink = "https://www.oudeis.co/"
  bio = [
    "I dabble in, and occasionally obsess over, technology and problems that bug me"
  ]

  # Gravitar author image
  email = "edward.romano@gmail.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "blog/"
  weight = 2

  [[menu.main]]
  name = "Projects"
  url = "projects/"
  weight = 3

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 4

  [params.social]
  email         = "oudeis.metis@gmail.com"
  twitter       = "https://twitter.com/oudeismetis"
  linkedin      = "https://www.linkedin.com/in/edromano/"
  stackoverflow = "https://stackoverflow.com/users/9173553/oudeis"
  github        = "https://github.com/oudeismetis"
  rss           = true
